import Color from 'color'
import { color as c } from '../color.ts'

/**
 * Link: https://code.visualstudio.com/api/references/theme-color
 * Doc: https://github.com/microsoft/vscode-docs/blob/main/api/references/theme-c.md
 */
const customizations: WorkbenchColorCustomizations = {
	'contrastActiveBorder': Color().alpha(0).hexa(),
	'contrastBorder': c.color3,
	'focusBorder': Color().alpha(0).hexa(),
	'foreground': c.color10,
	'widget.border': c.color4,
	'widget.shadow': Color().alpha(0).hexa(),
	'selection.background': c.color6,
	'icon.foreground': c.color10,
	'toolbar.hoverBackground': c.color4,
	'button.background': c.primary,
	'button.foreground': Color(c.primary).lighten(0.52).hex(),
  'button.border': Color().alpha(0).hexa(),
	'button.hoverBackground': Color(c.primary).darken(0.06).hex(),
  'button.secondaryBackground': c.color5,
  'button.secondaryForeground': c.color11,
	'dropdown.foreground': c.color10,
	'input.background': c.color4,
	'input.foreground': c.color11,
	'input.placeholderForeground': c.color9,
	'inputOption.activeBackground': c.primary,
	'inputOption.activeBorder': Color().alpha(0).hexa(),
	'inputOption.activeForeground': Color(c.primary).lighten(0.52).hex(),
	'inputOption.hoverBackground': c.color6,
	'scrollbar.shadow': Color().alpha(0).hexa(),
	'scrollbarSlider.activeBackground': c.color5,
	'scrollbarSlider.background': c.color4,
	'scrollbarSlider.hoverBackground': c.color5,
	'badge.foreground': Color(c.primary).lighten(0.52).hex(),
	'badge.background': c.primary,
	'progressBar.background': c.primary,
	'list.activeSelectionBackground': c.color4,
	'list.activeSelectionForeground': c.color10,
	'list.dropBackground': Color(c.color4).alpha(0.7).hexa(),
	'list.hoverBackground': Color(c.color4).alpha(0.7).hexa(),
	'list.inactiveSelectionBackground': Color(c.color4).alpha(0.7).hexa(),
  'list.dropBetweenBackground': c.color5,
	'activityBar.background': c.color2,
  'activityBar.dropBorder': Color(c.color4).alpha(0.7).hexa(),
	'activityBar.foreground': c.primary,
	'activityBar.inactiveForeground': c.color9,
	'activityBarBadge.background': c.primary,
	'activityBarBadge.foreground': Color(c.primary).lighten(0.52).hex(),
  'activityBarTop.foreground':  c.primary,
  'activityBarTop.activeBorder': c.primary,
  'activityBarTop.inactiveForeground': c.color9,
  'activityBarTop.dropBorder': Color(c.color4).alpha(0.7).hexa(),
	'sideBar.background': c.color2,
	'sideBarSectionHeader.background': c.color3,
	'sideBarSectionHeader.border': c.color4,
	'editorGroup.dropBackground': Color(c.color4).alpha(0.36).hexa(),
	'editorGroupHeader.tabsBackground': c.color2,
	'editorGroupHeader.tabsBorder': c.color3,
	'tab.activeBackground': c.color3,
	'tab.activeForeground': c.color10,
	'tab.border': c.color3,
	'tab.activeBorderTop': c.primary,
	'tab.inactiveBackground': Color().alpha(0).hexa(),
	'tab.inactiveForeground': c.color9,
	'editor.background': c.color2,
	'editor.foreground': c.color10,
	'editorLineNumber.foreground': c.color5,
	'editorLineNumber.activeForeground': c.color10,
	'editorCursor.foreground': c.color10,
	'editor.selectionBackground': Color(c.color10).alpha(0.2).hexa(),
	'editor.selectionHighlightBackground': Color(c.color10).alpha(0.2).hexa(),
	'editor.wordHighlightStrongBackground': Color(c.color10).alpha(0.3).hexa(),
	'editor.lineHighlightBorder': Color().alpha(0).hexa(),
	'editorWidget.background': c.color3,
	'editorWidget.border': c.color4,
	'editorSuggestWidget.focusHighlightForeground': Color(c.primary).lighten(0.1).hex(),
	'editorSuggestWidget.highlightForeground': c.primary,
	'editorSuggestWidget.selectedForeground': c.color12,
	'peekView.border': c.color4,
	'peekViewEditor.background': c.color3,
	'peekViewResult.background': c.color3,
	'peekViewResult.fileForeground': c.color10,
	'peekViewResult.selectionBackground': c.color4,
	'peekViewResult.selectionForeground': c.color10,
	'peekViewTitle.background': c.color3,
	'peekViewTitleLabel.foreground': c.primary,
	'panel.background': c.color2,
	'panel.dropBorder': c.primary,
	'panelTitle.activeBorder': c.primary,
	'panelTitle.activeForeground': c.primary,
	'panelTitle.inactiveForeground': c.color10,
	'statusBar.background': c.color2,
	'statusBar.foreground': c.color10,
	'statusBar.debuggingBackground': c.color2,
	'statusBar.debuggingForeground': c.color10,
	'statusBar.noFolderForeground': c.color10,
	'statusBar.noFolderBackground': c.color2,
	'statusBarItem.prominentBackground': c.color3,
	'statusBarItem.prominentHoverBackground': c.color3,
  'statusBarItem.remoteHoverForeground': Color(c.primary).lighten(0.52).hex(),
	'titleBar.activeBackground': c.color2,
	'titleBar.activeForeground': c.color10,
	'titleBar.border': c.color3,
	'menu.foreground': c.color10,
	'menu.background': c.color3,
	'menu.selectionBackground': c.color4,
	'menu.separatorBackground': c.color4,
	'menu.border': c.color4,
	'notifications.background': c.color3,
	'keybindingLabel.background': c.color4,
	'keybindingLabel.foreground': c.color10,
	'keybindingLabel.border': Color().alpha(0).hexa(),
	'keybindingLabel.bottomBorder': Color().alpha(0).hexa(),
	'terminal.foreground': c.color10,
	'debugToolBar.background': c.color3,
	'settings.headerForeground': c.color11,
	'breadcrumb.focusForeground': Color(c.primary).lighten(0.1).hex()
}


for (const key in customizations) {
	if (Object.prototype.hasOwnProperty.call(customizations, key)) {
		const value = customizations[key]
		if (value?.trim() !== '') {
			customizations[key] = value?.toLowerCase()
		}
	}
}

export const workbenchColorCustomizations = customizations
