import { color as c } from '../color.ts';
import chroma from 'chroma-js';

/**
 * Link: https://code.visualstudio.com/api/references/theme-color
 * Doc: https://github.com/microsoft/vscode-docs/blob/main/api/references/theme-c.md
 */
const customizations: WorkbenchColorCustomizations = {
  contrastActiveBorder: '#00000000',
  contrastBorder: c['color3.5'],
  focusBorder: '#00000000',
  foreground: c.color10,
  'widget.border': c.color4,
  'widget.shadow': '#00000000',
  'selection.background': c.color6,
  'icon.foreground': c.color10,
  'toolbar.hoverBackground': chroma(c.color5).alpha(0.5).hex(),
  'button.background': c.primary,
  'button.foreground': chroma(c.primary).brighten(2.5).hex(),
  'button.border': '#00000000',
  'button.hoverBackground': chroma(c.primary).darken(0.26).hex(),
  'button.secondaryBackground': c.color5,
  'button.secondaryForeground': c.color11,
  'dropdown.foreground': c.color10,
  'dropdown.listBackground': c.color3,
  'input.background': c.color4,
  'input.foreground': c.color11,
  'input.placeholderForeground': c.color9,
  'inputOption.activeBackground': c.primary,
  'inputOption.activeBorder': '#00000000',
  'inputOption.activeForeground': chroma(c.primary).brighten(2.5).hex(),
  'inputOption.hoverBackground': c.color6,
  'scrollbar.shadow': '#00000000',
  'scrollbarSlider.activeBackground': c.color5,
  'scrollbarSlider.background': c.color4,
  'scrollbarSlider.hoverBackground': c.color5,
  'badge.foreground': chroma(c.primary).brighten(2.5).hex(),
  'badge.background': c.primary,
  'progressBar.background': c.primary,
  'list.activeSelectionBackground': c.color4,
  'list.activeSelectionForeground': c.color10,
  'list.dropBackground': chroma(c.color4).alpha(0.6).hex(),
  'list.hoverBackground': chroma(c.color4).alpha(0.6).hex(),
  'list.inactiveSelectionBackground': chroma(c.color4).alpha(0.6).hex(),
  'list.dropBetweenBackground': c.color5,
  'activityBar.background': c.color2,
  'activityBar.dropBorder': chroma(c.color4).alpha(0.6).hex(),
  'activityBar.foreground': chroma(c.primary).brighten(0.38).hex(),
  'activityBar.inactiveForeground': c.color9,
  'activityBarBadge.background': c.primary,
  'activityBarBadge.foreground': chroma(c.primary).brighten(2.5).hex(),
  'activityBarTop.foreground': chroma(c.primary).brighten(0.38).hex(),
  'activityBarTop.activeBorder': c.primary,
  'activityBarTop.inactiveForeground': c.color9,
  'activityBarTop.dropBorder': chroma(c.color4).alpha(0.6).hex(),
  'sideBar.background': c['color2.5'],
  'sideBarSectionHeader.background': c['color3.5'],
  'sideBarSectionHeader.border': c['color4.5'],
  'editorGroup.dropBackground': chroma(c.color4).alpha(0.36).hex(),
  'editorGroupHeader.tabsBackground': c['color2.5'],
  'editorGroupHeader.tabsBorder': c['color3.5'],
  'tab.activeBackground': chroma(c.primary).alpha(0.08).hex(),
  'tab.activeForeground': c.color10,
  'tab.border': c['color3.5'],
  'tab.activeBorderTop': c.primary,
  'tab.inactiveBackground': '#00000000',
  'tab.inactiveForeground': c.color9,
  'tab.dragAndDropBorder': c.color5,
  'editor.background': c.color2,
  'editor.foreground': c.color10,
  'editorLineNumber.foreground': c.color5,
  'editorLineNumber.activeForeground': c.color10,
  'editorCursor.foreground': c.color10,
  'editor.selectionBackground': chroma(c.color10).alpha(0.3).hex(),
  'editor.selectionHighlightBackground': chroma(c.color10).alpha(0.2).hex(),
  'editor.wordHighlightStrongBackground': chroma(c.color10).alpha(0.3).hex(),
  'editor.lineHighlightBorder': '#00000000',
  'editorWidget.background': c.color3,
  'editorWidget.border': c.color4,
  'editorSuggestWidget.focusHighlightForeground': chroma(c.primary)
    .brighten(0.68)
    .hex(),
  'editorSuggestWidget.highlightForeground': c.primary,
  'editorSuggestWidget.selectedForeground': c.color12,
  'peekView.border': c.color4,
  'peekViewEditor.background': c.color3,
  'peekViewResult.background': c.color3,
  'peekViewResult.fileForeground': c.color10,
  'peekViewResult.selectionBackground': c.color4,
  'peekViewResult.selectionForeground': c.color10,
  'peekViewTitle.background': c.color3,
  'peekViewTitleLabel.foreground': c.primary,
  'panel.border': c['color3.5'],
  'panel.background': c['color2.25'],
  'panel.dropBorder': c.color5,
  'panelTitle.activeBorder': chroma(c.primary).brighten(0.38).hex(),
  'panelTitle.activeForeground': chroma(c.primary).brighten(0.38).hex(),
  'panelTitle.inactiveForeground': c.color10,
  'statusBar.background': c.color3,
  'statusBar.foreground': c.color10,
  'statusBar.debuggingBackground': c.color2,
  'statusBar.debuggingForeground': c.color10,
  'statusBar.noFolderForeground': c.color10,
  'statusBar.noFolderBackground': c.color2,
  'statusBarItem.prominentBackground': chroma(c.color5).alpha(0.5).hex(),
  'statusBarItem.hoverBackground': chroma(c.color5).alpha(0.5).hex(),
  'statusBarItem.remoteHoverForeground': chroma(c.primary).brighten(2.6).hex(),
  'titleBar.activeBackground': c.color3,
  'titleBar.activeForeground': c.color10,
  'titleBar.border': c.color4,
  'menu.foreground': c.color10,
  'menu.background': c.color3,
  'menu.selectionBackground': c.color4,
  'menu.separatorBackground': c.color4,
  'menu.border': c.color4,
  'notifications.background': c.color3,
  'keybindingLabel.background': c.color4,
  'keybindingLabel.foreground': c.color10,
  'keybindingLabel.border': '#00000000',
  'keybindingLabel.bottomBorder': '#00000000',
  'terminal.foreground': c.color10,
  'debugToolBar.background': c.color3,
  'settings.headerForeground': c.color11,
  'settings.focusedRowBackground': c.color3,
  'settings.rowHoverBackground': chroma(c.color3).alpha(0.6).hex(),
  'settings.dropdownBackground': c.color4,
  'settings.dropdownBorder': c.color4,
  'settings.checkboxBackground': c.color4,
  'breadcrumb.focusForeground': chroma(c.primary).brighten(0.6).hex(),
  'breadcrumb.background': c['color2.5'],
};

for (const key in customizations) {
  if (Object.prototype.hasOwnProperty.call(customizations, key)) {
    const value = customizations[key];
    if (value?.trim() !== '') {
      customizations[key] = value?.toLowerCase();
    }
  }
}

export const workbenchColorCustomizations = customizations;
