import { color as c } from '../color.ts';
import {
  transparent,
  hexAlpha,
  hexToLightness,
} from '../../../utils/culori.ts';

/**
 * Link: https://code.visualstudio.com/api/references/theme-color
 * Doc: https://github.com/microsoft/vscode-docs/blob/main/api/references/theme-c.md
 */
const customizations: WorkbenchColorCustomizations = {
  contrastActiveBorder: transparent,
  contrastBorder: c.color3,
  focusBorder: transparent,
  foreground: c.color10,
  'widget.border': c.color4,
  'widget.shadow': transparent,
  'selection.background': c.color6,
  'icon.foreground': c.color10,
  'toolbar.hoverBackground': c.color4,
  'button.background': c.primary,
  'button.foreground': hexToLightness(c.primary, 0.34),
  'button.border': transparent,
  'button.hoverBackground': hexToLightness(c.primary, -0.05),
  'button.secondaryBackground': c.color5,
  'button.secondaryForeground': c.color11,
  'dropdown.foreground': c.color10,
  'dropdown.listBackground': c.color3,
  'input.background': c.color4,
  'input.foreground': c.color11,
  'input.placeholderForeground': c.color9,
  'inputOption.activeBackground': c.primary,
  'inputOption.activeBorder': transparent,
  'inputOption.activeForeground': hexToLightness(c.primary, 0.34),
  'inputOption.hoverBackground': c.color6,
  'scrollbar.shadow': transparent,
  'scrollbarSlider.activeBackground': c.color5,
  'scrollbarSlider.background': c.color4,
  'scrollbarSlider.hoverBackground': c.color5,
  'badge.foreground': hexToLightness(c.primary, 0.34),
  'badge.background': c.primary,
  'progressBar.background': c.primary,
  'list.activeSelectionBackground': c.color4,
  'list.activeSelectionForeground': c.color10,
  'list.dropBackground': hexAlpha(c.color4, 0.6),
  'list.hoverBackground': hexAlpha(c.color4, 0.6),
  'list.inactiveSelectionBackground': hexAlpha(c.color4, 0.6),
  'list.dropBetweenBackground': c.color5,
  'activityBar.background': c.color2,
  'activityBar.dropBorder': hexAlpha(c.color4, 0.6),
  'activityBar.foreground': hexToLightness(c.primary, 0.08),
  'activityBar.inactiveForeground': c.color9,
  'activityBarBadge.background': c.primary,
  'activityBarBadge.foreground': hexToLightness(c.primary, 0.34),
  'activityBarTop.foreground': hexToLightness(c.primary, 0.08),
  'activityBarTop.activeBorder': c.primary,
  'activityBarTop.inactiveForeground': c.color9,
  'activityBarTop.dropBorder': hexAlpha(c.color4, 0.6),
  'sideBar.background': c.color2,
  'sideBarSectionHeader.background': c.color3,
  'sideBarSectionHeader.border': c.color4,
  'editorGroup.dropBackground': hexAlpha(c.color4, 0.36),
  'editorGroupHeader.tabsBackground': c.color2,
  'editorGroupHeader.tabsBorder': c.color3,
  'tab.activeBackground': hexAlpha(c.primary, 0.08),
  'tab.activeForeground': c.color10,
  'tab.border': c.color3,
  'tab.activeBorderTop': c.primary,
  'tab.inactiveBackground': transparent,
  'tab.inactiveForeground': c.color9,
  'tab.dragAndDropBorder': c.color5,
  'editor.background': c.color2,
  'editor.foreground': c.color10,
  'editorLineNumber.foreground': c.color5,
  'editorLineNumber.activeForeground': c.color10,
  'editorCursor.foreground': c.color10,
  'editor.selectionBackground': hexAlpha(c.color10, 0.3),
  'editor.selectionHighlightBackground': hexAlpha(c.color10, 0.2),
  'editor.wordHighlightStrongBackground': hexAlpha(c.color10, 0.3),
  'editor.lineHighlightBorder': transparent,
  'editorWidget.background': c.color3,
  'editorWidget.border': c.color4,
  'editorSuggestWidget.focusHighlightForeground': hexToLightness(
    c.primary,
    0.1,
  ),
  'editorSuggestWidget.highlightForeground': c.primary,
  'editorSuggestWidget.selectedForeground': c.color12,
  'peekView.border': c.color4,
  'peekViewEditor.background': c.color3,
  'peekViewResult.background': c.color3,
  'peekViewResult.fileForeground': c.color10,
  'peekViewResult.selectionBackground': c.color4,
  'peekViewResult.selectionForeground': c.color10,
  'peekViewTitle.background': c.color3,
  'peekViewTitleLabel.foreground': c.primary,
  'panel.border': c.color3,
  'panel.background': c.color2,
  'panel.dropBorder': c.color5,
  'panelTitle.activeBorder': hexToLightness(c.primary, 0.08),
  'panelTitle.activeForeground': hexToLightness(c.primary, 0.08),
  'panelTitle.inactiveForeground': c.color10,
  'statusBar.background': c.color2,
  'statusBar.foreground': c.color10,
  'statusBar.debuggingBackground': c.color2,
  'statusBar.debuggingForeground': c.color10,
  'statusBar.noFolderForeground': c.color10,
  'statusBar.noFolderBackground': c.color2,
  'statusBarItem.prominentBackground': c.color3,
  'statusBarItem.prominentHoverBackground': c.color3,
  'statusBarItem.remoteHoverForeground': hexToLightness(c.primary, 0.34),
  'titleBar.activeBackground': c.color2,
  'titleBar.activeForeground': c.color10,
  'titleBar.border': c.color3,
  'menu.foreground': c.color10,
  'menu.background': c.color3,
  'menu.selectionBackground': c.color4,
  'menu.separatorBackground': c.color4,
  'menu.border': c.color4,
  'notifications.background': c.color3,
  'keybindingLabel.background': c.color4,
  'keybindingLabel.foreground': c.color10,
  'keybindingLabel.border': transparent,
  'keybindingLabel.bottomBorder': transparent,
  'terminal.foreground': c.color10,
  'debugToolBar.background': c.color3,
  'settings.headerForeground': c.color11,
  'settings.focusedRowBackground': c.color3,
  'settings.rowHoverBackground': hexAlpha(c.color3, 0.6),
  'settings.dropdownBackground': c.color4,
  'settings.dropdownBorder': c.color4,
  'settings.checkboxBackground': c.color4,
  'breadcrumb.focusForeground': hexToLightness(c.primary, 0.1),
};

for (const key in customizations) {
  if (Object.prototype.hasOwnProperty.call(customizations, key)) {
    const value = customizations[key];
    if (value?.trim() !== '') {
      customizations[key] = value?.toLowerCase();
    }
  }
}

export const workbenchColorCustomizations = customizations;
