import chroma from 'chroma-js';
import { baseBlockColor, baseColor } from '../color.ts';

export const getWorkbenchConfig = (color: Color = baseColor): Workbench => {
  const base = color;

  const baseBorder = base.color3;
  const basePrimaryForeground = chroma(base.primary).brighten(2.5).hex();

  return {
    contrastActiveBorder: '#00000000',
    contrastBorder: baseBorder,
    focusBorder: '#00000000',
    foreground: base.color10,
    'widget.border': base.color4,
    'widget.shadow': '#00000000',
    'selection.background': base.color6,
    'icon.foreground': base.color10,
    'toolbar.hoverBackground': chroma(base.color4).alpha(0.6).hex(),
    'button.background': base.primary,
    'button.foreground': basePrimaryForeground,
    'button.border': '#00000000',
    'button.hoverBackground': chroma(base.primary).darken(0.26).hex(),
    'button.secondaryBackground': base.color5,
    'button.secondaryForeground': base.color11,
    'dropdown.foreground': base.color10,
    'dropdown.listBackground': base.color3,
    'input.background': base.color4,
    'input.foreground': base.color11,
    'input.placeholderForeground': base.color9,
    'inputOption.activeBackground': base.primary,
    'inputOption.activeBorder': '#00000000',
    'inputOption.activeForeground': basePrimaryForeground,
    'inputOption.hoverBackground': base.color6,
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.activeBackground': base.color5,
    'scrollbarSlider.background': base.color4,
    'scrollbarSlider.hoverBackground': base.color5,
    'badge.foreground': basePrimaryForeground,
    'badge.background': base.primary,
    'progressBar.background': base.primary,
    'list.activeSelectionBackground': base.color4,
    'list.activeSelectionForeground': base.color10,
    'list.dropBackground': chroma(base.color4).alpha(0.6).hex(),
    'list.hoverBackground': chroma(base.color4).alpha(0.6).hex(),
    'list.inactiveSelectionBackground': chroma(base.color4).alpha(0.6).hex(),
    'list.dropBetweenBackground': base.color5,
    'activityBar.background': base.color2,
    'activityBar.dropBorder': chroma(base.color4).alpha(0.6).hex(),
    'activityBar.foreground': chroma(base.primary).brighten(0.38).hex(),
    'activityBar.inactiveForeground': base.color9,
    'activityBarBadge.background': base.primary,
    'activityBarBadge.foreground': basePrimaryForeground,
    'activityBarTop.foreground': chroma(base.primary).brighten(0.38).hex(),
    'activityBarTop.activeBorder': base.primary,
    'activityBarTop.inactiveForeground': base.color9,
    'activityBarTop.dropBorder': chroma(base.color4).alpha(0.6).hex(),
    'sideBar.background': base.color2,
    'sideBarActivityBarTop.border': baseBorder,
    'sideBarSectionHeader.background': base.color3,
    'sideBarSectionHeader.border': base.color4,
    'editorGroup.dropBackground': chroma(base.color4).alpha(0.36).hex(),
    'editorGroupHeader.tabsBackground': base.color2,
    'editorGroupHeader.tabsBorder': baseBorder,
    'tab.activeBackground': chroma(base.primary).alpha(0.08).hex(),
    'tab.activeForeground': base.color10,
    'tab.border': baseBorder,
    'tab.activeBorderTop': base.primary,
    'tab.inactiveBackground': '#00000000',
    'tab.inactiveForeground': base.color9,
    'tab.dragAndDropBorder': base.color5,
    'editor.background': base.color2,
    'editor.foreground': base.color10,
    'editorLineNumber.foreground': base.color5,
    'editorLineNumber.activeForeground': base.color9,
    'editorCursor.foreground': base.color10,
    'editor.selectionBackground': chroma(base.color10).alpha(0.3).hex(),
    'editor.selectionHighlightBackground': chroma(base.color10)
      .alpha(0.2)
      .hex(),
    'editor.wordHighlightStrongBackground': chroma(base.color10)
      .alpha(0.3)
      .hex(),
    'editor.lineHighlightBorder': '#00000000',
    'editorWidget.background': base.color3,
    'editorWidget.border': base.color4,
    'editorSuggestWidget.focusHighlightForeground': chroma(base.primary)
      .brighten(0.68)
      .hex(),
    'editorSuggestWidget.highlightForeground': base.primary,
    'editorSuggestWidget.selectedForeground': base.color12,
    'peekView.border': base.color4,
    'peekViewEditor.background': base.color3,
    'peekViewResult.background': base.color3,
    'peekViewResult.fileForeground': base.color10,
    'peekViewResult.selectionBackground': base.color4,
    'peekViewResult.selectionForeground': base.color10,
    'peekViewTitle.background': base.color3,
    'peekViewTitleLabel.foreground': base.primary,
    'panel.border': baseBorder,
    'panel.background': base.color2,
    'panel.dropBorder': base.color5,
    'panelTitle.activeBorder': chroma(base.primary).brighten(0.38).hex(),
    'panelTitle.activeForeground': chroma(base.primary).brighten(0.38).hex(),
    'panelTitle.inactiveForeground': base.color10,
    'statusBar.background': base.color2,
    'statusBar.foreground': base.color10,
    'statusBar.focusBorder': base.color3,
    'statusBar.debuggingBackground': base.color2,
    'statusBar.debuggingForeground': base.color10,
    'statusBar.noFolderForeground': base.color10,
    'statusBar.noFolderBackground': base.color2,
    'statusBarItem.prominentBackground': chroma(base.color4).alpha(0.6).hex(),
    'statusBarItem.hoverBackground': chroma(base.color4).alpha(0.6).hex(),
    'statusBarItem.remoteHoverForeground': basePrimaryForeground,
    'statusBarItem.remoteHoverBackground': chroma(base.primary)
      .brighten(-0.2)
      .hex(),
    'titleBar.activeBackground': base.color2,
    'titleBar.activeForeground': base.color10,
    'titleBar.border': baseBorder,
    'menu.foreground': base.color10,
    'menu.background': base.color3,
    'menu.selectionBackground': base.color4,
    'menu.separatorBackground': base.color4,
    'menu.border': base.color4,
    'notifications.background': base.color3,
    'keybindingLabel.background': base.color4,
    'keybindingLabel.foreground': base.color10,
    'keybindingLabel.border': '#00000000',
    'keybindingLabel.bottomBorder': '#00000000',
    'terminal.foreground': base.color10,
    'debugToolBar.background': base.color3,
    'settings.headerForeground': base.color11,
    'settings.focusedRowBackground': base.color3,
    'settings.rowHoverBackground': chroma(base.color3).alpha(0.6).hex(),
    'settings.dropdownBackground': base.color4,
    'settings.dropdownBorder': base.color4,
    'settings.checkboxBackground': base.color4,
    'breadcrumb.focusForeground': chroma(base.primary).brighten(0.6).hex(),
  };
};

export const getWorkbenchBlockConfig = (
  color: Color = baseBlockColor(),
): Workbench => {
  const baseBorderColor = color['color3.5'];

  return {
    ...getWorkbenchConfig(color),
    contrastBorder: baseBorderColor,
    'toolbar.hoverBackground': chroma(color.color5).alpha(0.6).hex(),
    'sideBar.background': color['color2.5'],
    'sideBarActivityBarTop.border': baseBorderColor,
    'sideBarSectionHeader.background': color['color3.5'],
    'sideBarSectionHeader.border': color['color4.5'],
    'editorGroupHeader.tabsBackground': color['color2.5'],
    'editorGroupHeader.tabsBorder': baseBorderColor,
    'tab.border': baseBorderColor,
    'panel.border': baseBorderColor,
    'panel.background': color['color2.25'],
    'statusBar.background': color['color2.75'],
    'statusBar.focusBorder': color['color3.5'],
    'statusBarItem.prominentBackground': chroma(color.color5).alpha(0.5).hex(),
    'statusBarItem.hoverBackground': chroma(color.color5).alpha(0.5).hex(),
    'titleBar.activeBackground': color.color3,
    'titleBar.border': color.color4,
    'breadcrumb.background': color['color2.5'],
  };
};
